name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: mskelton/setup-pnpm@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm fmt:check
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm ts
